### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by escapecat** [yizt/aiia_elec_miner#1]
您好，我也是在找电力行业相关的数据集，因为网上这方面的文本数据实在太少，如果您有之前留存的txt文本，能发我一份吗？不胜感激，邮箱：602623932@qq.com

**Comment by yizt** [comment]
@escapecat 已发您邮箱

**Comment by escapecat** [comment]
@yizt  非常感谢！

**Comment by LiuYaKu** [comment]
您好，我们项目组最近正在做电力行业知识图谱项目，正在找电力行业相关的数据集，您的数据集能不能也发我一份，万分感激，邮箱：2510278539@qq.com

**Comment by SeekPoint** [comment]
yk_data@126.com
不可以报名了，方便发一份数据吗，谢谢

**Comment by yizt** [comment]
@LiuYaKu @loveJasmine 已发两位邮箱！

**Comment by LiuYaKu** [comment]
万分感谢，但是数据已经过期了，无法下载，您能重新发一份吗，麻烦您了

**Comment by yizt** [comment]
@LiuYaKu @loveJasmine 抱歉，没有看到，直接转的邮件，已经重发了

**Comment by LiuYaKu** [comment]
@yizt 万分感谢

**Comment by SeekPoint** [comment]
@yizt 非常感谢

**Comment by 1031fantay** [comment]
您好，我们在做电力行业词典的方向，正在找电力行业相关的数据集，您的数据集能不能也发我一份，万分感激，邮箱541730524@qq.com

**Comment by DAVEZJ** [comment]
您好，我也是在找电力行业相关的数据集，因为网上这方面的文本数据实在太少，能否将数据集分享给我以分，不胜感激，邮箱：darkness127@163.com

**Comment by 1031fantay** [comment]
我也在找这方面的数据，如果有人发给我，我到时候会发给你的，你如果找到电力相关词汇，也可以跟我共享。






------------------ 原始邮件 ------------------
发件人: "DAVEZJ"<notifications@github.com>;
发送时间: 2019年7月21日(星期天) 晚上7:31
收件人: "yizt/aiia_elec_miner"<aiia_elec_miner@noreply.github.com>;
抄送: "绝杀8023"<541730524@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yizt/aiia_elec_miner] 数据集 (#1)




您好，我也是在找电力行业相关的数据集，因为网上这方面的文本数据实在太少，能否将数据集分享给我以分，不胜感激，邮箱：darkness127@163.com

**Comment by elsy07** [comment]
你好~我就不抄上面几位的了 同恳求电力数据集！邮箱: xux001@gmail.com 谢谢！

**Comment by 1031fantay** [comment]
对不起，我也没有收到他们发给我的数据集，所以帮不到你。但是我有在github上看到有人用scala做过那个国家电网的比赛，虽然我看不太懂那个程序，但是他分出了一些词汇，如有需要，可以交流一下，因为我也是新手，才开始接触这方面




------------------ 原始邮件 ------------------
发件人: "elsy07"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 晚上6:09
收件人: "yizt/aiia_elec_miner"<aiia_elec_miner@noreply.github.com>;
抄送: "541730524"<541730524@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yizt/aiia_elec_miner] 数据集 (#1)




你好~我就不抄上面几位的了 同恳求电力数据集！邮箱: xux001@gmail.com 谢谢！

**Comment by huige555551** [comment]
您好，我毕业论文正在做电力行业项目，正在找电力行业相关的数据集，您的数据集能不能也发我一份，万分感激，邮箱：1026367919@qq.com

**Comment by hjy2011** [comment]
您好，在做领域词汇挖掘的实验，您的数据集能发一份到我邮箱吗，万分感谢：
yao.mitcn@qq.com

**Comment by 2hip3ng** [comment]
您好，最近在做电力文本分析，能分享一下数据集吗，万分感激，邮箱：zhipengwang1121@163.com

**Comment by fangsuwan** [comment]
您好，最近在做电力文本分析，能分享一下数据集吗，万分感激，邮箱：1300702190@qq.com

**Comment by yizt** [comment]
@all 抱歉！有很多人都在请求数据集，个人无法确认各位的用途，另外赛事主办方也未授权传播。

**Comment by chen-huicheng** [comment]
您好，我毕业论文是电力行业项目相关的知识图谱，正在找电力行业相关的数据集，您的数据集能不能也发我一份，万分感激，邮箱：374955376@qq.com

**Comment by pxlsdz** [comment]
您好，我正在找电力行业相关的数据集，您的数据集能不能也发我一份，万分感激，邮箱：sdz_zju@126.com

**Comment by heqianpei** [comment]
您好，我们正在做电力行业知识图谱相关研究，您的数据集能不能也发我一份，万分感激！邮箱：hqp@zju.edu.cn

**Comment by fangsuwan** [comment]
不好意思，该数据集为我实验室合作项目方提供，不方便分享
&nbsp;


苏、笛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qianpei ***@***.***&gt;; 
发送时间: 2023年7月25日(星期二) 下午2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yizt/aiia_elec_miner] 数据集 (#1)





 
***@***.***

**Comment by heqianpei** [comment]
好的，感谢回复~---- 回复的原邮件 ***@***.***>发送日期2023年07月25日 14:42 ***@***.***> 抄送人Qianpei ***@***.***>***@***.***>主题Re: [yizt/aiia_elec_miner] 数据集 (#1)
不好意思，该数据集为我实验室合作项目方提供，不方便分享

&nbsp;





苏、笛

***@***.***







&nbsp;









------------------&nbsp;原始邮件&nbsp;------------------

发件人: "Qianpei ***@***.***&gt;;  

发送时间: 2023年7月25日(星期二) 下午2:30

收件人: ***@***.***&gt;;  

抄送: ***@***.***&gt;; ***@***.***&gt;;  

主题: Re: [yizt/aiia_elec_miner] 数据集 (#1)











  

***@***.***

  

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you commented.Message ID: ***@***.***&gt;

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yizt/aiia_elec_miner/issues/1#issuecomment-1649211208",
"url": "https://github.com/yizt/aiia_elec_miner/issues/1#issuecomment-1649211208",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LathMio** [comment]
> 您好，我也是在找电力行业相关的数据集，因为网上这方面的文本数据实在太少，如果您有之前留存的txt文本，能发我一份吗？不胜感激，邮箱：[602623932@qq.com](mailto:602623932@qq.com)

你好，这个电力行业的文本数据集您这还有存档吗，可以转发我一份吗，不胜感激 邮箱13225202696@163.com

**Comment by iridescentiii** [comment]
您好，我也在找电力行业的相关数据，可以麻烦您发我一份吗，非常感谢，邮箱2946899874@qq.com

**Comment by Benjamin-Ricky** [comment]
> [@escapecat](https://github.com/escapecat) 已发您邮箱

请问可以发一份给我吗，最近在找这方面的数据集，谢谢你，邮箱：chenyu528491@gmail.com
